name: check_node_version

on:
  workflow_dispatch:

jobs:
  check-node-version:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: node --version
